// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZlvBDEzVLWurO-RwyZwnqOeEUyLTNlpY',
    appId: '1:926287133153:web:98084ab760e1a1e2ec7aa0',
    messagingSenderId: '926287133153',
    projectId: 'crud-firebase-cli',
    authDomain: 'crud-firebase-cli.firebaseapp.com',
    storageBucket: 'crud-firebase-cli.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL42-nCNtlrUHDJeUGUoArxssJbnFMmaY',
    appId: '1:926287133153:android:28df586f676ea899ec7aa0',
    messagingSenderId: '926287133153',
    projectId: 'crud-firebase-cli',
    storageBucket: 'crud-firebase-cli.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsRXwxG4oGiGAP_Qngc2rmvtncoChn8pE',
    appId: '1:926287133153:ios:834fa391daad5c4dec7aa0',
    messagingSenderId: '926287133153',
    projectId: 'crud-firebase-cli',
    storageBucket: 'crud-firebase-cli.appspot.com',
    iosBundleId: 'com.example.firebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsRXwxG4oGiGAP_Qngc2rmvtncoChn8pE',
    appId: '1:926287133153:ios:63e4c85c5feb1779ec7aa0',
    messagingSenderId: '926287133153',
    projectId: 'crud-firebase-cli',
    storageBucket: 'crud-firebase-cli.appspot.com',
    iosBundleId: 'com.example.firebaseCrud.RunnerTests',
  );
}
